### ISSUE TITLE
Getting below issue while deploy on server

### ISSUE THREAD

**Issue by ChiragsinhCW** [suchorski/springboot-keycloak-server#14]
Mixed Content: The page at ‘[https://auth.keycloak.aws.com/admin/master/console/ 7](https://auth.keycloak.aws.com/admin/master/console/)’ was loaded over HTTPS, but requested an insecure resource ‘[http://auth.keycloak.aws.com/realms/master/protocol/openid-connect/3p-cookies/step1.html 6](http://auth.keycloak.aws.com/realms/master/protocol/openid-connect/3p-cookies/step1.html)’. This request has been blocked; the content must be served over HTTPS.

![a65ff63bbd7e897fe018e90d14c2c84da2f44e15](https://github.com/user-attachments/assets/8f9bca0e-22e2-4456-9ec1-2f5b258ad931)

**Comment by suchorski** [comment]
Perhaps something related to AWS. I use it on my VPS normally
