### ISSUE TITLE
Upgrade Keycloak version to  22.0.0

### ISSUE THREAD

**Issue by DhimanRishabh** [suchorski/springboot-keycloak-server#6]
can we upgrading Keycloak to version 22.0.0 and Spring Boot to version 3.1.1

**Comment by suchorski** [comment]
O Will take a look. You can send PR too

**Comment by suchorski** [comment]
I'm trying without success. The method onStartup is not being called. You can check the developing branch to see if you can fix it. Will continue to try, Thanks

**Comment by ebremer** [comment]
See #7

**Comment by suchorski** [comment]
@ebremer did the update... thanks!
